geographic/continents/urls.py
from django.urls import path
from continents.views import ContinentsView

app_name = 'continents'

urlpatterns = [
    path('', ContinentsView.as_view(), name='continents'),
]

geographic/countries/urls.py
from django.urls import path
from countries.views import (
    HomeView,
    TagsView,
    CountryDetailView,
    CountrySearchView,
)


app_name = 'countries'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('tags/', TagsView.as_view(), name='tags'),
    path('<str:code>/', CountryDetailView.as_view(), name='country_detail_code'),
    path('search/<query>/', CountrySearchView.as_view(), name='country_search')
]

geographic/geographic/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('countries/', include('countries.urls', namespace='countries')),
    path('continents/', include('continents.urls', namespace='continents')),
    path('people/', include('people.urls'))
]

geographic/people/urls.py
from django.urls import path, include
from people.views import register

urlpatterns = [
    path('register/', register, name="register"),
]

geographic/continents/models.py
from django.db import models

# Create your models here.


class Continent(models.Model):
    name = models.CharField(max_length=255)
    translate = models.CharField(max_length=255)
    color = models.CharField(max_length=255)

    def __str__(self):
        return self.name

geographic/countries/models.py
from django.db import models

# Create your models here.


class ActiveManager(models.Manager):
    """
    Creacion de un Manager para que cuando se use solo traiga
    los Countries activos. Para que funcione hay que colocar en
    los modelos que van a usar este Manager la variable:
    active_manager = ActiveManager
    """

    def get_queryset(self):
        return super().get_queryset().filter(active=True)


class Country(models.Model):
    CODES_CHOICES = (
        ('Colombia', 'CO'),
        ('Estados Unidos', 'USA'),
        ('Mexico', 'MX')
    )

    name = models.CharField(max_length=255)
    code = models.CharField(max_length=3, choices=CODES_CHOICES)
    # code = models.CharField(max_length=3)
    continent = models.ForeignKey(
        'continents.Continent',
        on_delete=models.CASCADE
    )
    active = models.BooleanField(default=True)
    active_manager = ActiveManager()
    objects = models.Manager()

    def __str__(self):
        return self.name

    # Si quiero que el campo code tome solo ciertos datos dados (que el usuario
    # no inserte lo que quiera, si no lo que se le da a escoger):
    # code = models.CharField(max_length=3, choices=CODES_CHOICES)

geographic/people/models.py
from django.db import models

# Create your models here.

class Person(models.Model):
    first_name = models.CharField(max_length=255)
    nacionality = models.ManyToManyField('countries.Country')
    father = models.OneToOneField('self', on_delete=models.CASCADE, blank=True, null=True)

geographic/people/forms.py
from django import forms
from countries.models import Country


class RegisterForm(forms.Form):
    first_name = forms.CharField(label='first name')
    nacionality = forms.ModelMultipleChoiceField(queryset=Country.objects.all())

geographic/continents/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import View
from django.views.generic import TemplateView #  Importa la clase View

# Create your views here.

class ContinentsView(TemplateView):
    template_name = 'continents/home.html'

    def get_context_data(self, *args, **kwargs):
        """ Por medio de esta función se pasan datos al template"""
        america = {'name': 'America'}
        europa = {'name': 'Europa'}
        asia = {'name': 'Asia'}

        continents = [america, europa, asia]

        return {'continents': continents}

geographic/countries/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse,Http404
from django.views.generic import View
from django.views.generic import TemplateView  # Importa la clase View
from django.views.generic.list import ListView

from countries.models import Country
# Create your views here.


class HomeView(TemplateView):
    # Estas clases solo aceptan los metodos GET, POST o DISPATCH
    # si se quiere que la vista se comporte de diferente forma
    # dependiendo del metodo debo definir cada medoto:
    # get(), post()
    # si quiero que sin importar el metodo se comporte de la misma forma
    # dispatch()
    template_name = 'countries/home.html'


class TagsView(TemplateView):
    template_name = 'countries/tags.html'


class CountryDetailView(TemplateView):
    template_name = 'countries/country_detail.html'

    def get_context_data(self, *args, **kwargs):
        country = get_object_or_404(Country, code=kwargs['code'])

        return {'country': country}


class CountrySearchView(ListView):
    template_name = 'countries/search.html'

    def get_queryset(self):
        query = self.kwargs['query']
        return Country.objects.filter(name__contains=query)

geographic/people/views.py
from django.shortcuts import render
from django.http import JsonResponse
from people.forms import RegisterForm
from people.models import Person
# Create your views here.


def register(request):
    form = RegisterForm(request.POST or None)

    if form.is_valid():
        data = form.cleaned_data
        person = Person.objects.create(
            first_name=data['first_name'],
            father=data['father']
        )

        for country in data['nacionality']:
            person.nacionality.add(country)

        return JsonResponse(
            {
                'name': person.first_name,
                'father': str(person.father),
                'nacionality': ','.join([str(country) for country in person.nacionality.all()])
            }
        )

    return render(request, 'people/register.html', {'form': form})

geographic/continents/templates/continents/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge"> 
        <meta charset="utf-8">
        <title>
            {% block title%} {% endblock%}
        </title>
    </head>
    <body>
        {% block content %}
            
        {% endblock %}
    </body> 
</html>

geographic/continents/templates/continents/home.html
{% extends "continents/base.html" %}

{% block title%}
    Continents
{% endblock %}

{% block content %}
    <p>Continentes</p>
    {% for continent in continents%}
        <p> {{ continent.name }} </p>
    {% endfor %}
    
{% endblock %}

geographic/countries/templates/countries/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge"> 
        <meta charset="utf-8">
        <title>
            {% block title%} {% endblock%}
        </title>
    </head>
    <body>
        {% block content %}

        {% endblock %}
    </body> 
</html>

geographic/countries/templates/countries/country.html
{% for country in countries %}
            <p>Nombre: {{ country.name }}</p>
            <p>Código: {{ country.code }}</p>
{% endfor%}

geographic/countries/templates/countries/country_detail.html
{% extends "countries/base.html" %}
{% block content %}
    <h1>Detalle de los paises</h1>
    <p>Código: {{ code }}</p>

	{% include 'countries/country.html'%}

{% endblock %}

geographic/countries/templates/countries/home.html
{% extends "countries/base.html"%}

{% block title %}
    Home
{% endblock %}

{% block content %}
    
    <p>Desde home.html</p>

    <p>El siguiente código desde country.html:</p>

    {% include "countries/country.html"%}

    <a href="{% url "countries:tags" %}">Tags</a><br>
    <a href="{% url "continents:continents" %}">Continentes</a><br>

    <p>Genera automaticamente los links de los diferentes paises:</p>
    {% for country in countries %}
        <a href="{{ country.url }}">{{country.name}}</a><br>
    {% endfor %}

    <p>Con el metodo reverse:</p>
    {% for country in countries %}
        <a href="{{ country.url }}">{{ country.name }}</a>
    {% endfor %}

{% endblock %}



geographic/countries/templates/countries/search.html
{% extends 'countries/base.html' %}

{% block content %}

	{% for country in object_list %}
		{% include 'countries/country.html' %}
	{% endfor %}

{% endblock %}

geographic/countries/templates/countries/tags.html
{% extends "countries/base.html" %}

{% block title %}
    Tags
{% endblock %}

{% block content %}

    {% comment %}
        Esto es un comentario
    {% endcomment %}

    <p>Lorem: {% lorem %}</p>

    <p>Fecha actual {% now "Y-m-d" %}</p>

    {% comment %}
        La variable de abajo 'countries' la trae desde context_processor.py
        tambien esta disponible en 'home.html'
    {% endcomment %}

    
{% endblock %}

geographic/people/templates/people/register.html
{% extends "countries/base.html" %}
{% block title %}
    Register
{% endblock %}
{% block content %}
    <form action="." method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="" value="Registro">
    </form>
{% endblock %}